spring:
  application:
    name: ccsbico
  jackson:
    default-property-inclusion: non-empty
    deserialization:
      accept-empty-string-as-null-object: true
      accept-empty-array-as-null-object: true
      fail-on-null-for-primitives: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    multipart:
      max-file-size: 1MB
      max-request-size: 3MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply@ccsbi.com
    password: donotreply123
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
  
      
  datasource:
    username: root 
    password: ccsbi@12
    name: ccsbitrans
    url: jdbc:mysql://localhost:3306/ccsbitrans?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
        
  
management:
  server:
    servlet:
      context-path: /actuator
  info:
    git:
      mode: full
    
logging:
  level:
    root: warn
    com.ccsbi.coin: debug
    
springfox:
  documentation:
    swagger:
      v2:
        path: /

---
contactus:
  username: contactus@ccsbi.com
  password: contactus123

---
app:
  email: NO
  sms: NO      
